### ISSUE TITLE
Método para llenar el título del docente

### ISSUE THREAD

**Issue by vulopez** [LMS-Efpem/LMS#14]
# Descripción

Puesto que en nuestro modelo de BD el profesor tiene un título. Existen dos maneras propuestas para poder mostrarlo.

1. Uno añadiendo una tabla sencilla, que indique el máximo título alcanzado:
![Image](https://github.com/LMS-Efpem/LMS/assets/111790061/7309629c-05a3-494d-84b9-4bf0c6fb5d8f)

2. Y este que es más elaborado, pero indica el progreso del docente en educación superior muy útil para algunas instituciones.
Pueden ver una demo en [este enlace](https://vulopez.github.io/title-field/).

¿Qué método deberíamos utilizar?

PD.: _¿El administrador también debería tener título?
¿Qué método usar con en Administrador en caso afirmativo?_

**Comment by mbrend** [comment]
Yo voto por el primer método! 👌

**Comment by Jehydi** [comment]
Voto por el primer metodo

**Comment by bm18if** [comment]
Si el primer método
